apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roshambo-game
  namespace: openshift-gitops
spec:
  destination:
    namespace: rpsgame
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/redhat-developer-demos/rps-game-manifests.git 
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
